your_first_game: Rust example for screen_size
Grabbed this from https://github.com/godot-rust/godot-rust/blob/master/examples/dodge_the_creeps/src/player.rs#L34

To fit the examples in other languages this should be used:

```rs
impl Player {
  #[export]
    fn _ready(&mut self, owner: &Area2D) {
      self.screen_size = viewport.size();
    }
}
```

But in rustlang we don't have access to 'viewport' from this scope:

```
error[E0425]: cannot find value `viewport` in this scope
  --> examples/dodge_the_creeps/src/player.rs:36:28
   |
36 |         self.screen_size = viewport.size();
   |                            ^^^^^^^^ not found in this scope
```

Thus it requires use of unsafe code.

Should be peer-reviewed by godot-rust, provided as-is to the best of my
ability

Signed-off-by: Jacob Hrbek <kreyren@fsfe.org>