Error in gdexample.cpp
When adding the getter and setter functions to the example project a void has been added to the constructor in line 439 which was previously not there (in line 213) and is also causing the error C2533: constructors not allowed a return type. Simply removing it again fixes it.